/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData iconAwesomeBook = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconAwesomeHotjar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconOpenChat = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMaterialPerson = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconAwesomePencilAlt = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMaterialTimeline = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconIonicIosWater = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMetroAir = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
